### ISSUE TITLE
Support for typescript

### ISSUE THREAD

**Issue by vTrip** [maxs15/react-native-spinkit#105]
Is it possible to have typescript definitions for this library?

**Comment by nartc** [comment]
@vTrip 
```typescript
declare module 'react-native-spinkit' {
  import React from 'react';

  export type SpinnerType =
    | 'CircleFlip'
    | 'Bounce'
    | 'Wave'
    | 'WanderingCubes'
    | 'Pulse'
    | 'ChasingDots'
    | 'ThreeBounce'
    | 'Circle'
    | '9CubeGrid'
    | 'WordPress'
    | 'FadingCircle'
    | 'FadingCircleAlt'
    | 'Arc'
    | 'ArcAlt'
    | 'Plane';

  export type SpinnerProps = {
    isVisible: boolean;
    color?: string;
    size?: number;
    type?: SpinnerType;
  };

  const Spinner: React.ComponentType<SpinnerProps>;
  export default Spinner;
}
```

While waiting for typescript support, you can do the following:
1. At your root, make a `.d.ts` file. You can name it anything you want.
2. Copy and paste the snippet above.

**Comment by steffenagger** [comment]
@vTrip It looks like `isVisible` is also optional (see: https://github.com/maxs15/react-native-spinkit/blob/5c08bdb546cc6d54769b5f19e9a129f857c75be6/index.js#L41).
But thanks! Just what I needed.
