### ISSUE TITLE
Could not find com.github.ybq:Android-SpinKit:1.1.0

### ISSUE THREAD

**Issue by puyanLiu** [maxs15/react-native-spinkit#111]
* What went wrong:
A problem occurred configuring project ':app'.
      > Could not resolve all dependencies for configuration ':react-native-spinkit:_debugPublishCopy'.
         > Could not find com.github.ybq:Android-SpinKit:1.1.0.

**Comment by tnyavdc** [comment]
Looks like the Android SpinKit has updated to 1.2.0 and dropped 1.1.0. `Changing compile 'com.github.ybq:Android-SpinKit:1.1.0`' in the react-native-spinkit build.gradle to `compile 'com.github.ybq:Android-SpinKit:1.2.0'` works

**Comment by maxs15** [comment]
Fix merged in 1.2.0
