### ISSUE TITLE
'compile' is obsolete and has been replaced with 'implementation'

### ISSUE THREAD

**Issue by tethridge** [maxs15/react-native-spinkit#119]
The Gradle file needs to be updated 'implementation' instead of 'compile'.  I am seeing this warning after a Gradle sync.

WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: react-native-spinkit

**Comment by jose920405** [comment]
+1
