### ISSUE TITLE
package android.support.annotation does not exist

### ISSUE THREAD

**Issue by ChauVV** [maxs15/react-native-spinkit#126]
My current React-Native:

"react": "16.8.6",
"react-native": "0.60.3",
"react-native-spinkit": "^1.4.1",

but on Android i hit an essue:

 error: package android.support.annotation does not exist

**Comment by auguszou** [comment]
+1

**Comment by Stormsher** [comment]
@ChauVV Hi, I made fix for it in my PR: https://github.com/maxs15/react-native-spinkit/pull/127

also you can just use my fork: https://github.com/Stormsher/react-native-spinkit
