### ISSUE TITLE
[Android] Not able to pass through a variable as the size definition

### ISSUE THREAD

**Issue by bsinc** [maxs15/react-native-spinkit#15]
When I use a number for the size it works fine, but using a variable causes errors.

When I run it on Android I get this error:
"Error while updating property 'size' of a view managed by: RNSpinkit"

Here is the relative code:

```
var deviceWidth = Dimensions.get('window').width;
var deviceHeight = Dimensions.get('window').height;

var smallSpinner = deviceWidth/2;
var largeSpinner = deviceWidth/1.75;

<Spinner type='Bounce' color='#ffffff' size={largeSpinner}/>
<Spinner type='Bounce' color='#ffffff' size={smallSpinner}/>
```

The same happens when using states: 

```
getInitialState() {
        return {
            smallSpinner: deviceWidth/2,
            largeSpinner: deviceWidth/1.75
        }
    },

<Spinner type='Bounce' color='#ffffff' size={this.state.largeSpinner}/>
<Spinner type='Bounce' color='#ffffff' size={this.state.smallSpinner}/>
```

This works fine on iOS.

**Comment by wkh237** [comment]
Hi @bsinc , I've located the problem, this error happens when you're using a float number for the size. 
I'll try to make a pull request to fix it, and you may use `parseInt` before passing the value to component for this moment :)
