### ISSUE TITLE
Encountered an error while persisting cache

### ISSUE THREAD

**Issue by alexjhannan** [maxs15/react-native-spinkit#19]
Awesome package by the looks of it. When I tried to get it working, I ran into this error:

>[node-haste] Encountered an error while persisting cache:
>> SyntaxError: /Users/AlexMac/Projects/PalateCleanser/node_modules/react-native-spinkit/scripts/rnpm-prelink.js: 'return' outside of function (42:0)
>> // etc, can post if full log is helpful

I install via npm, linked up with rnpm, and my test code is very simple: 

> import Spinner from 'react-native-spinkit';
>  // (in render)
>  \<Spinner isVisible={true} size={24} type={"Circle"} color="#000000"/\>

 On screen, the loading spinner does not show up and a thin red box of the appropriate size appears instead.

Thanks much for any help!

**Comment by maxs15** [comment]
Thanks for the feedback @alexjhannan.
Looks like an issue with the rnpm autolinking script, I pushed a potential fix in the new version (0.1.2).
Could you please try and let me know ? Thanks

**Comment by alexjhannan** [comment]
Works perfectly now. Thanks so much! Great support and a great package.
