### ISSUE TITLE
support android

### ISSUE THREAD

**Issue by buhe** [maxs15/react-native-spinkit#2]
Awsome project!
React native for android released. support android?

hare

**Comment by maxs15** [comment]
Yeah I know, finally !
I hope so in the coming weeks.
If you wanna add the support by any chance, PR are welcomed :)

**Comment by niftylettuce** [comment]
:+1:

**Comment by niftylettuce** [comment]
I'd give a bug bounty reward to have this.

**Comment by dangnelson** [comment]
+1

**Comment by bfarrgaynor** [comment]
+1

**Comment by derese** [comment]
+1

**Comment by maxs15** [comment]
Well guys it's finally here :) Please read the [note](https://github.com/maxs15/react-native-spinkit/issues/4)
I'm closing this issue
