### ISSUE TITLE
Android build fails because it fails to find Build Tools revision 23.0.3

### ISSUE THREAD

**Issue by justim** [maxs15/react-native-spinkit#21]
When building this project for Android it fails with the following error:

> failed to find Build Tools revision 23.0.3

Would it be a good idea to replace your version with the same as Facebook uses for React Native? That should not introduce a problem and solves it for people that only have Build Tools revision `23.0.1` installed.
https://github.com/facebook/react-native/blob/master/ReactAndroid/build.gradle#L219

I have verified that this change solves the problem for me.

**Comment by shidhincr** [comment]
@maxs15 Can you have a look at this issue ? It's been a blocker

**Comment by maxs15** [comment]
Hey guys,
You only have to update the Android SDK Build-tools from your Android SDK Manager.
Better learn how to update your libraries or you'll be stuck as well when RN will update its dependencies :)

**Comment by justim** [comment]
I agree with you that updating the Android SDK Build-tools would solve the situation, but a lot of people never did something with Android and to come to this conclusion might be too much hassle. It would save some people time when it just works (tm).

**Comment by MacKentoch** [comment]
When experiencing the issue on my application I went to github to check issues and maybe to ask a fix.

But now I better understand and finally I agree with @maxs15: updating Android SDK tools is the way to deal with it.

**Just my point of view:**
Even for newcomers (*in android dev*), [ReactNative is nicely documented](https://facebook.github.io/react-native/docs/getting-started.html) and using `android studio` is even easier for a beginner.

I'm an iOS dev not an android one. But as ReactNative gave me opportunity to create applications in android too I feel like obvious to learn smoothly about android ecosystem to make better apps or just to extend my culture.

Note : @justim nice picture, I was fan of this serie 👍

**Comment by odino** [comment]
It's more like with a 1 liner we can avoid people to worry about this kind of stuff now and deal with it later, when - possibly - react native wants you to upgrade to `23.0.somethingnewer` and there will be a plethora of people with the same problem who know how to fix it.

Avoiding this issue doesnt cost anything, keeping it there just means creating impediments for free :)

My 2 c

**Comment by mfkp** [comment]
FYI I forked this project and just changed the one line in `build.gradle` to use 23.0.1 to avoid forcing all our developers to install a different sdk version just to build this one project.

Would rather be able to point it to the source repo, but this is the easiest option for now.

**Comment by faxioman** [comment]
Really @maxs15 , you made a great job ... but this little change can save the day to many devs out there ;)

**Comment by maxs15** [comment]
Okay guys, my new year resolution is to update the build tool version if it can really help some devs out there ! ;)
Just pushed it in 1.0.1  (be careful starting 1.0 the plugin needs RN >= 0.40)
