### ISSUE TITLE
Plugin not works for me

### ISSUE THREAD

**Issue by angel3509268** [maxs15/react-native-spinkit#23]
I am using your module for my project

/**
 * Created by hero on 2016-07-02.
 */

import React, { Component } from 'react';
import {
    AppRegistry,
    StyleSheet,
    Text,
    View,
    TouchableOpacity
} from 'react-native';

var Spinner = require('react-native-spinkit');

var MainPage = React.createClass({

    render()
    {
        return(
            <View style={styles.container}>
                <Spinner isVisible={true} size={120} type="Pulse" color="#00ff00"/>
            </View>
        );
    }
});

var styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#ffffff'
    }
});
export default MainPage;

But when I display this page I get only rectangle with red border.
Can you please tell me what's wrong in my project?

**Comment by adamjacob** [comment]
I had the same issue, I quit simulator and run the project again.  Works perfect now 😄

**Comment by wkh237** [comment]
Try close packager and restart it again, looks like native modules not got linked

**Comment by maiklez** [comment]
I have the same issue, 
I try to restart the packager, the simulator, the app in the phone and the computer :) but nothing change.

I still have the rectangle with red border.

**Comment by maxs15** [comment]
The red border means the native library isn't linked to your project

**Comment by matthewwoop** [comment]
@angel3509268  @maiklez  

be sure to link the native library with as it says in the README

`rnpm link react-native-spinkit`

**Comment by maiklez** [comment]
yes! that was the problem! Thanks! Solved to me!

**Comment by karan101292** [comment]
There is a problem with `rnpm link react-native-spinkit`. Sometimes it adds RNSpinkitPackage dependency to MainActivity.java instead of MainApplication.java

Solution:
Follow this step manually
https://github.com/maxs15/react-native-spinkit/wiki/Manual-linking---Android#in-androidappsrcmainjavacomexamplemainapplicationjava-add-the-rnspinkitpackage-dependency
