### ISSUE TITLE
[Android] Cannot animate multiple spinners

### ISSUE THREAD

**Issue by yianyue** [maxs15/react-native-spinkit#31]
When there are multiple spinners visible in an app, only the last spinner animates.

The project is using RN 0.32 and react-native-spinkit 0.1.3

Tested on Moto X emulator (Android 4.4.4) and OnePlus 3 (Android 6.0.1)

**Comment by maxs15** [comment]
Hmm weird, doesn't it work on IOS ?

**Comment by yianyue** [comment]
Yes, it works fine on IOS

**Comment by gordonpro** [comment]
Android. I got this issue. Android 6.0.1 , React Native 0.30.

**Comment by gijoehosaphat** [comment]
I have the same issue on Android. Android 5, RN 0.34.0

**Comment by maxs15** [comment]
I won't be able to push a fix right now, in the meantime if anybody could look at this issue it would be nice :)
The first thing we should know is if the issue is related to the RN wrapper or the Android dependency (https://github.com/ybq/Android-SpinKit)

**Comment by SHRoberts91** [comment]
I have this issue on android as well as something that I feel like is related to this and was brought up in #32 . 
Issue #1: So my spinner just blinks in and out, and doesn't actually spin.
Issue#2: When I try to have multiple spinners going on the same scene, then only one will show, sometimes not even that one.

**Comment by maxs15** [comment]
I just pushed a new version (0.1.5) with the fix.
Thanks again to @wkh237 !
