### ISSUE TITLE
Native component for "RNSpinkit" does not exist

### ISSUE THREAD

**Issue by MikeJSX** [maxs15/react-native-spinkit#33]
Everything is working fine for iOS but for Android i have this warning and instead of spinner i see red square

**Comment by MikeJSX** [comment]
Ok, I found a solution. I didn't have needed code in - android/app/src/main/java/com/example/MainApplication.java.
I had different path to this directory so rnpm did't do what it used to. Maybe you need to correct documentation or add 'recommended' way to install as manual.

**Comment by lucianomlima** [comment]
If you use react-native link react-native-spinkit, it works.

**Comment by navneetccna** [comment]
run react-native link react-native-spinkit but still same message

**Comment by kis25791** [comment]
Hi any solution for this issue till now?

**Comment by navneetccna** [comment]
@kis25791 not yet :(

**Comment by maxs15** [comment]
Check the manual linking in the README, and verify that everything is correct

**Comment by sahir** [comment]
I did all steps but it's not working in Android  'ReactNativeJS: Warning: Native component for "RNSpinkit" does not exist'. Anyone find the Solution?

**Comment by pjamrozowicz** [comment]
For anyone else having this error:
Make sure you have `compile project(':react-native-spinkit')` in your `android/app/build.gradle` file. react-native link didn't add this line there for me and that's why I was getting an error

**Comment by zlienqwe** [comment]
Hi any solution for this issue now? I need help..

**Comment by zlienqwe** [comment]
I react-native run-android again, somehow problem solved.

**Comment by bchhabra2490** [comment]
@pjamrozowicz  I already had this line but it's still not working. I am using expo client on Android and also performed all the steps given in README.

**Comment by amitkumarsingh1991** [comment]
hey , 
run react-native link react-native-spinkit

**Comment by khalifathul** [comment]
May be you've cache problem. try this command after link the component it should work.
rm -rf node_modules && rm -rf ~/.rncache && yarn && react-native run-ios

**Comment by Pradeep119** [comment]
try  "react-native link react-native-spinkit"  its work for me

**Comment by martinjego** [comment]
try reinstalling the app by running react-native run-android/react-native run-ios. It usually solves the problem.

**Comment by Pradeep119** [comment]
Ok thanks dude.

**Comment by MashoodAli-Official** [comment]
> try "react-native link react-native-spinkit" it works for me

Thanks :) now it's working <3
