### ISSUE TITLE
Red square issue running from react-native cli to emulator for IOS

### ISSUE THREAD

**Issue by bernardn98** [maxs15/react-native-spinkit#36]
We ran these commands and copy/paste your code (https://github.com/maxs15/react-native-spinkit/blob/master/Example/index.ios.js) but could not get it to work.  The emulator is showing a red square above the text menu.  It threw a warning in the emulator that it could not find the Spinner component but the warning goes away when I switch from using require to import.  However the animation runs fine with the same code when deploying to the emulator from xcode.  Let us know if there's something else we can try.  THANKS!

npm install react-native-spinkit@latest --save
rnpm link react-native-spinkit

**Comment by johnchourajr** [comment]
Same error here.

**Comment by jonrh** [comment]
I had the same red square but not sure if it's exactly the same issue. The React Native Package Manager [RNPM](https://github.com/rnpm/rnpm) has been merged into React Native core. Running the following commands in my project folder worked for me:

```bash
npm install react-native-spinkit@latest --save
react-native link react-native-spinkit
```

Then in my React component I load it in with ES2015 module syntax and use the Spinner component like the example shows:

```jsx
import Spinner from "react-native-spinkit";

// Inside render()
<Spinner isVisible={true} size={40} type={"ThreeBounce"} color={"black"} />
```

**Comment by yuanfang-fn** [comment]
react-native link react-native-spinkit
(node:32024) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

**Comment by bernardn98** [comment]
Thanks everyone will close this issue.  There was another library we had in our project that conflicted with this one.
