### ISSUE TITLE
Cannot install by npm install react-native-spinkit@latest --save

### ISSUE THREAD

**Issue by jp928** [maxs15/react-native-spinkit#44]
always get 0.1.5 installed even forcibly install by `npm install react-native-spinkit@1.0 --save `

node version 5.12.0
npm version 3.8.6
react-native version 0.40

**Comment by maxs15** [comment]
Sorry I forgot to publish the last version on npm, try again and let me know !
Thanks

**Comment by jp928** [comment]
Thanks for your reply.
Do you migrate to Yarn, what is the best way to follow ?
