### ISSUE TITLE
spinkit doesn't animate on Android with RN 0.42.0

### ISSUE THREAD

**Issue by ronadi** [maxs15/react-native-spinkit#53]
"react": "~15.4.1",
"react-native": "0.42.0",
"react-native-spinkit": "^1.0.2"

- react-native link (done)

Testing use Example react-native-spinkit.

Tested on Ios => OK
Tested on android => can show but not animate (run on device lenovo with android version 6.0.1)

![screenshot_2017-03-15-11-33-41-421](https://cloud.githubusercontent.com/assets/733941/23933865/151a5592-0974-11e7-8b05-797bc0b41732.jpeg)

**Comment by hnhm** [comment]
Same problem with "react": "~15.4.0",  "react-native": "0.41.2", "react-native-spinkit": "^1.0.2" running on Android device.

**Comment by appsthatmatter** [comment]
had the same issue, but it was my fault. I disabled the animations in the android developer options!

**Comment by ronadi** [comment]
@appsthatmatter yes correct same with me, forgot to close issue
