### ISSUE TITLE
RNPM seems not supporting this plugin

### ISSUE THREAD

**Issue by VansonLeung** [maxs15/react-native-spinkit#6]
Hi, I run "rnpm link" but failed to link react-native-spinkit's iOS dependencies.
I am still investigating why, because I am not familiar with RNPM yet.

**Comment by maxs15** [comment]
Oh interesting, I've never used rnpm yet but we should support it of course.
Let me know if you find the issue

**Comment by VansonLeung** [comment]
I found out the reason I could not link this library.
https://github.com/rnpm/rnpm/issues/109
It is not related to your plugin.
