### ISSUE TITLE
Linking while using other modules

### ISSUE THREAD

**Issue by iBicha** [maxs15/react-native-spinkit#64]
I think it is worth mentionning in the docs that manual linking is required if a module such as `react-native-navigation` is used

**Comment by MossP** [comment]
Why is that? If anything I think the docs should maybe just say..
```
react-native link react-native-spinkit
```
..instead of a generic link statement?

**Comment by iBicha** [comment]
For some reason linking fails and the android project doesn't build anymore, thus i had to do it manually

**Comment by iBicha** [comment]
I don't have enough details to reproduce this issue, I'll close it for now, feel free to reopen if this reoccurs.
