### ISSUE TITLE
Remove the deprecation warning PropTypes from React v15.5+

### ISSUE THREAD

**Issue by gauravds** [maxs15/react-native-spinkit#65]
[React.PropTypes is deprecated as of React v15.5](https://facebook.github.io/react/docs/typechecking-with-proptypes.html), Convert this to `import PropTypes from 'prop-types';` [click here more detail](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html).

**Comment by maxs15** [comment]
The issue has been fixed.
Thanks
