### ISSUE TITLE
Android - Error while updating property 'color' of a view managed by: RNSpinkit

### ISSUE THREAD

**Issue by MossP** [maxs15/react-native-spinkit#67]
react-native: 0.45.1
react: 16.0.0.alpha-12
react-native-spinkit: 1.0.3 (upgraded from 1.0.2 recently)

Spinner usage on Android triggers error?

![screenshot_2017-06-22-14-28-03](https://user-images.githubusercontent.com/10449262/27436818-4abb3356-5758-11e7-80d6-96c27f81b51d.png)

usage:
```
<Spinner isVisible={true} size={80} type={'Wave'} color={'#ffffff'}/>
```

**Comment by MossP** [comment]
It seems that unlinking and relinking the project is required after upgrading to 1.0.3. That seems to have fixed it for me.

**Comment by minicase** [comment]
I have the same issue

**Comment by MossP** [comment]
Did you try relinking the component?
