### ISSUE TITLE
Submit to cocoapods so native iOS developers can integrate it with existing iOS project

### ISSUE THREAD

**Issue by portwatcher** [maxs15/react-native-spinkit#7]
CocoaPods is a centralized package manager for Objective-C and Swift projects.
https://cocoapods.org/

Here is the guide how to submit
https://guides.cocoapods.org/making/index.html

**Comment by maxs15** [comment]
If you're using react-native I don't understand why you couldn't use npm.
All the RN components are distributed through npm, give it a try ;)

**Comment by portwatcher** [comment]
We made a Web browser that renders React Native and this project is a Objective-C project, that's how we need CocoaPods to make package management more convenient.

http://docs.tinydust.cn/React-Native-iOS/%E4%BB%8B%E7%BB%8D
http://docs.tinydust.cn/React-Native-iOS/%E8%BF%90%E8%A1%8C%20React%20Native%20%E7%9A%84%E6%AD%A5%E9%AA%A4

However, we can still integrate by dragging RNSpinKit.xcodeproj in. Feel free to close it.

**Comment by maxs15** [comment]
Oh nice, I see.
I'm sorry but your case is too particular, maybe [RNPM](https://github.com/rnpm/rnpm) could help you out
