### ISSUE TITLE
Warning: PropTypes has been moved to a separate package. 

### ISSUE THREAD

**Issue by agersoncgps** [maxs15/react-native-spinkit#74]
I am getting these three warning after upgraded to rn v46.

Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)

Warning: React.createClass is no longer supported. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement. 

Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.

**Comment by ahmed3mar** [comment]
Try

`yarn add maxs15/react-native-spinkit`

**Comment by maxs15** [comment]
The issue has been fixed.
Thanks
