### ISSUE TITLE
RNSpinkitPackage is not abstract and does not override abstract method createJSModules() in ReactPackage

### ISSUE THREAD

**Issue by antseburova** [maxs15/react-native-spinkit#78]
Hi,

After upgrading to version 1.1.0, my Android build fails with the following error:
```
RNSpinkitPackage is not abstract and does not override 
abstract method createJSModules() in ReactPackage
```
RN version is 0.43.4.

Could you please take a look at it?

Thank you,
Mila

**Comment by maxs15** [comment]
The version 1.1.0 is for RN 0.47.
Use the version 1.0.3, it should be alright 👍

**Comment by antseburova** [comment]
Got it, thank you!
