### ISSUE TITLE
"Tried to register two views with the same name RNSpinkit" error with React Native 0.49.3

### ISSUE THREAD

**Issue by ihor** [maxs15/react-native-spinkit#86]
**react-native-spinkit version**
1.1.1

**react-native version**
0.49.3

**STR**

Import the package:
```import Spinner from 'react-native-spinkit';```

**ER**: Everything works
**AR**: The app is crashing with "Tried to register two views with the same name RNSpinkit" error.
<img width="317" alt="screen shot 2017-10-19 at 19 16 04" src="https://user-images.githubusercontent.com/490943/31784463-079873f6-b502-11e7-949c-4709db793a1b.png">

**Comment by ihor** [comment]
CNR with RN 0.50.1

**Comment by NasarudinAbdulShukor** [comment]
hi, can you share what is the issue on your side? I am having the same kind of error but instead of RNSpinKit, it is RNSVGSvgView. Thank you

**Comment by DavitVosk** [comment]
Hello. I face the same problem. Can you please describe how fix the problem?

**Comment by SirPhemmiey** [comment]
Any fix for this?
