### ISSUE TITLE
Deprecated library issue (The SDK Build Tools revision (23.0.1) is too low for project ':react-native-spinkit'. Minimum required is 25.0.0)

### ISSUE THREAD

**Issue by Nitingadhiya** [maxs15/react-native-spinkit#96]
We have create project with latest react-native version. then installed spin-kit library
after I will run "react-native run-android" . but we have facing below error : 

**FAILURE: Build failed with an exception.**

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-spinkit'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':react-native-spinkit'. Minimum required is 25.0.0

**Project react-native version:** 
  "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-spinkit": "^1.1.1",

**Comment by JakeRawr** [comment]
+1

**Comment by happyEgg** [comment]
+1

**Comment by happyEgg** [comment]
@maxs15

**Comment by maxs15** [comment]
Fixed in 1.5.0 :)
